// <auto-generated />
using Electronics_Items_Management.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Electronics_Items_Management.Migrations
{
    [DbContext(typeof(ElectronicDatabase))]
    partial class ElectronicDatabaseModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("Electronics_Items_Management.Models.Brand_Detail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Brand_Branch_Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Brand_Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Brand_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Brand_Detail");
                });

            modelBuilder.Entity("Electronics_Items_Management.Models.Category_Detail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Category_Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Product")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Category_Detail");
                });

            modelBuilder.Entity("Electronics_Items_Management.Models.Customer_Detail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Customer_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Delivery_Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customer_Detail");
                });

            modelBuilder.Entity("Electronics_Items_Management.Models.Order_Detail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("Customer_DetailId")
                        .HasColumnType("int");

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Product_DetailId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Customer_DetailId");

                    b.HasIndex("Product_DetailId");

                    b.ToTable("Order_Detail");
                });

            modelBuilder.Entity("Electronics_Items_Management.Models.Product_Detail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("Brand_DetailId")
                        .HasColumnType("int");

                    b.Property<int>("Category_DetailId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Product_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Brand_DetailId");

                    b.HasIndex("Category_DetailId");

                    b.ToTable("Product_Detail");
                });

            modelBuilder.Entity("Electronics_Items_Management.Models.Order_Detail", b =>
                {
                    b.HasOne("Electronics_Items_Management.Models.Customer_Detail", "Customer_Detail")
                        .WithMany()
                        .HasForeignKey("Customer_DetailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Electronics_Items_Management.Models.Product_Detail", "Product_Detail")
                        .WithMany()
                        .HasForeignKey("Product_DetailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer_Detail");

                    b.Navigation("Product_Detail");
                });

            modelBuilder.Entity("Electronics_Items_Management.Models.Product_Detail", b =>
                {
                    b.HasOne("Electronics_Items_Management.Models.Brand_Detail", "Brand_Detail")
                        .WithMany()
                        .HasForeignKey("Brand_DetailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Electronics_Items_Management.Models.Category_Detail", "Category_Detail")
                        .WithMany()
                        .HasForeignKey("Category_DetailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand_Detail");

                    b.Navigation("Category_Detail");
                });
#pragma warning restore 612, 618
        }
    }
}
